# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[cava.waybar]
# 'cava.sh waybar' configuration
max_instances = 2 # Maximum number of cava instances // fix and workaround when waybar won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7
standby = "â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–â–"

[cava.stdout]
# 'cava.sh stdout' configuration
max_instances = 4 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "â–â–‚â–ƒâ–„â–…â–†â–‡â–ˆ"
width = 20
range = 7         # Number of (bars -1)
standby = "ğŸ¶"

[cava.hyprlock]
# 'cava.sh hyprlock' configuration
max_instances = 4 # Maximum number of cava instances // fix and workaround when a process won't kill 'cava ' process
bar = "ğŸŒ‘ğŸŒ’ğŸŒ“ğŸŒ”ğŸŒ•ğŸŒ–ğŸŒ—ğŸŒ˜"
width = 20
range = 7
standby = "ğŸ¶"

[weather]
temperature_unit='f'	# Temperature unit to Â°C or Â°F ('c' or 'f')
time_format='12'		# Time format ('12h or 24h')
windspeed_unit='mph'	# Windspeed unit ('kh/h' or 'mph')
show_icon= true			# Show the weather icon in waybar
show_location= true	    # Show the location in waybar
show_today= true		# Detailed description of today in tooltip
forecast_days= 3 		# Number of days to show forecast (0-3)
location = '34.244318, -89.008904'			# Location/coordinates string for the weather output
